apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mustgathers.redhatcop.redhat.io
spec:
  group: redhatcop.redhat.io
  names:
    kind: MustGather
    listKind: MustGatherList
    plural: mustgathers
    singular: mustgather
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MustGather is the Schema for the mustgathers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MustGatherSpec defines the desired state of MustGather
          properties:
            caseID:
              description: The is of the case this must gather will be uploaded to
              type: string
            caseManagementAccountSecretRef:
              description: the secret container a username and password field to be
                used to authenticate with red hat case management systems
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            mustGatherImages:
              description: 'The list of must gather images to run, optional, it will
                default to: quay.io/openshift/origin-must-gather:latest'
              items:
                type: string
              type: array
            serviceAccountRef:
              description: the service account to use to run the must gather job pod,
                defaults to default  +kubebuilder:default:="{Name:default}"
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
          required:
          - caseID
          - caseManagementAccountSecretRef
          type: object
        status:
          description: MustGatherStatus defines the observed state of MustGather
          properties:
            completed:
              type: boolean
            lastUpdate:
              format: date-time
              type: string
            reason:
              type: string
            status:
              enum:
              - Success
              - Failure
              type: string
          required:
          - completed
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
