apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .ObjectMeta.Name }}
  namespace: {{ .ObjectMeta.Namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - entrypoint:
        - /bin/bash
        - -c
        - /usr/local/bin/upload
        image: quay.io/redhat-cop/must-gather-operator:latest
        name: upload
        volumeMounts:
        - mountPath: /must-gather-output
          name: must-gather-output
        - mountPath: /must-gather-upload
          name: must-gather-output
        env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: case-management-secret
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: case-management-secret
              key: password
        - name: caseid
          value: "{{ .Spec.CaseID }}"
        - name: must_gather_output
          value: /must-gather-output
        - name: must_gather_upload
          value: /must-gather-upload                    
      initContainers:      
{{- range $index, $element := .Spec.MustGatherImages }}      
      - command:
        - /usr/bin/gather
        image: {{ $element }}
        name: gather-{{ $index }}
        volumeMounts:
        - mountPath: /must-gather-output
          name: must-gather-output
{{- end }}
      serviceAccountName: {{ .Spec.ServiceAccountRef.Name }}
      volumes:
      - emptyDir: {}
        name: must-gather-output
      - emptyDir: {}
        name: must-gather-upload
      - name: case-management-secret
        secret:
          secretName: {{ .Spec.CaseManagementAccountSecretRef.Name }}                
  backoffLimit: 4
